install:
  - ps: if ((Get-Command scoop -ErrorAction SilentlyContinue) -eq $null) { iex (new-object net.webclient).downloadstring('https://get.scoop.sh') }
  - ps: scoop bucket add extras
  - ps: scoop update *
  - ps: scoop install visualc rktools2k3
build_script:
  - cl isProcessRunning.cpp
test_script:
  - isProcessRunning.exe 0
  - powershell -f test.ps1
cache:
- '%USERPROFILE%\scoop'